### ISSUE TITLE
Доработки формирования URL на edge

### ISSUE THREAD

**Issue by ttyS15** [just-work/django-video-transcoding#21]
1) урлов может быть несколько 
2) нужно задавать не префикс, а шаблон для гибкости

https://github.com/just-work/django-video-transcoding/blob/master/src/video_transcoding/admin.py#L57

https://git.just-work.org/mediaforce/beautymedia/merge_requests/46#note_79445

**Comment by tumb1er** [comment]
Making two separate env variables:
```
VIDEO_EDGES = 'https://edge-1.localhost,https://edge-2.localhost'
```
This will contain domains for static load balancing (player receives multiple root playlist links and tries it ono-by-one)

```
VIDEO_URL = '{edge}/hls/{filename}.1080p.mp4/index.m3u8'
```
This will be final root playlist link like https://edge-1.localhost/hls/12341234asdfqwerzxcv123412341234.1080p.mp4/index.m3u8
